# Service Provider
sps:
  - entityid: PPA-Dev
    assertionconsumerservices:
      - index: 0
        isdefault: true
        binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST
        location: http://localhost:3000/backend/v1/sso/saml
    certificate: "MIIFajCCA1Kg...\n...\n..."
# Identity Provider
tls-ca: hack/tls-setup/certs/ca.pem
tls-certificate: hack/tls-setup/certs/idp.pem
tls-private-key: hack/tls-setup/certs/idp-key.pem
# Users
users:
  - name: domain\some.user
    password: "$2a$10$HeK6p2u08vBHg/5Tao6p1ud992wa3rC.tsEi/ZwDV1fLrUr/tmd/q" #password1
    attributes:
      object_sid:
        - S-1-5-21-1234567-891011
      email:
        - some.user@domain.com
      groups:
        - Development
